---
# tasks file for nginx
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx service
  service:
    name: nginx
    state: started
    enabled: true

- name: copy nginx configration file
  copy:
    src: wordpress.conf
    dest: /etc/nginx/conf.d/

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
