---
# tasks file for wordpress
- name: Install prerequisites
  apt: 
    name: aptitude 
    update_cache: yes 
    state: latest 
    force_apt_get: yes

- name: Install LAMP Packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'apache2', 'mysql-client', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

- name: Install PHP Extensions
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
    owner: apache
    group: apache
    mode: 0775

- name: Configure WordPress
  copy:
    src: wp-config.php
    dest: /var/www/html/wordpress/
    owner: apache
    group: apache
    mode: 0644

- name: Start Apache
  service:
    name: apache2
    state: started
    enabled: true

- name: restart apahe
  service:
    name: apache2
    state: reloaded



