---
- name: Install required packages
  dnf:
    name: 
      - httpd
      - php
      - php-mysqlnd
      - php-fpm
      - php-json
      - wget
      - mariadb105
    state: present

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    owner: apache
    group: apache
    remote_src: yes
    mode: 0775

- name: Configure WordPress
  template:
    src: wp-config.php
    dest: /var/www/html/wordpress/wp-config.php
    owner: apache
    group: apache
    mode: 0644

- name: Start Apache
  service:
    name: httpd
    state: started
    enabled: true
