---
# tasks file for wordpress
- name: Install required packages
  dnf:
    name: 
      - httpd
      - php
      - php-mysqlnd
      - php-fpm
      - php-json
      - wget
    state: present

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Configure WordPress
  copy:
    src: wp-config.php
    dest: /var/www/html/my-lb-1873265896.ap-south-1.elb.amazonaws.com/
    owner: apache
    group: apache
    mode: 0644

- name: Start Apache
  service:
    name: httpd
    state: started
    enabled: true

- name: restart apahe
  service:
    name: httpd
    state: reloaded



